# --------------------------------------------------------------------------
# Name:        Find the Difference
# Author(s):   Phu Tran
# --------------------------------------------------------------------------
"""
    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one 
    more letter at a random position.

    Find the letter that was added in t.

    Example:
        Input:
            s = "abcd"
            t = "abcde"
        Output:
            e
        Explanation:
            'e' is the letter that was added.
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dic_s = {}
        dic_t = {}
        
        for i in range(len(t)):
            if i == len(s):
                dic_t[t[i]] = dic_t.get(t[i], 0) +1
            else:
                dic_s[s[i]] = dic_s.get(s[i], 0) +1
                dic_t[t[i]] = dic_t.get(t[i], 0) +1
        
        for key in dic_t:
            if dic_s.get(key, -1) != dic_t[key]:
                return key
                
            
        
            
        
        
        
        
        
        
        
        
    
        
            
        
 



        
'''other methods (from other submissions)
##################################################
def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        stot = 0
        ttot = 0
        for i in s:
            stot += ord(i)
        for k in t:
            ttot += ord(k)
            
        diff = ttot-stot
        return chr(diff)
##################################################
def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        c=0
        for i in s:
            c=c^ord(i)
        for j in t:
            c=c^ord(j)
        return chr(c)
##################################################
def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        hm = {}
        
        for c in s :
            if c in hm :
                hm[c] += 1
            else :
                hm[c] = 1
        
        for c in t :
            if c in hm :
                hm[c] -= 1 
            else :
                return c
        
        for k in hm.keys() :
            if hm[k] < 0 :
                return k
##################################################
'''
